-- DEV_WIP.sql
-- Scratch pad for in-progress DB changes.
-- Cleared: 2026-04-24
-- Last merged: batch canonicalisation — inbound.usp_create_inbound_line,
--              inbound.usp_create_expected_unit,
--              inbound.usp_receive_inbound_line (schema fix + UPPER batch)
--              api user ordering fix (moved after usp_create_user definition)
