-- DEV_WIP.sql
-- Scratch pad for in-progress DB changes.
-- Cleared: 2026-04-24
-- Last merged: is_system_role on auth.roles, api role + user,
--              usp_roles_get excludes system roles,
--              fn_is_system_user now role-based
