-- DEV_WIP.sql
-- Scratch pad for in-progress DB changes.
-- Cleared: 2026-05-15
-- Last merged:
--   inbound.usp_receive_inbound_line: UPPER() removed from bin lookup
--   warehouse.usp_putaway_confirm_task: UPPER() removed from bin comparison
--   warehouse.usp_bin_to_bin_move_create: UPPER() removed from bin lookup
--   warehouse.usp_bin_to_bin_move_confirm: UPPER() removed from bin comparison
--   audit.v_sku_changes: JSON paths updated from $.Data.Data to $.Data.Outcome
--
-- Pending (next WIP cycle):
--   outbound.usp_pick_create: still has UPPER() on destination bin
--   outbound.usp_pick_confirm: still has UPPER() on scanned bin
