using System.Text.RegularExpressions;

namespace PeasyWare.Tools.Commands;

/// <summary>
/// Concatenates all scripts in Database/Scripts/ into DEV_AllInOneInOneGo.sql
/// in alphanumeric folder + file order.
///
/// Each atomic script carries a standalone USE PW_Core_DEV; GO header so it can
/// be run directly in Azure Data Studio. This command strips that header from
/// each file and emits a single USE/GO at the top of the output instead.
///
/// Output: Database/DEV/DEV_AllInOneInOneGo.sql
/// </summary>
internal static class BuildAllInOneCommand
{
    public static int Run(string[] args)
    {
        string scriptsRoot;
        string dbRoot;

        try
        {
            scriptsRoot = ToolsConfig.GetScriptsRoot();
            dbRoot      = ToolsConfig.GetDatabaseRoot();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"ERROR: {ex.Message}");
            return 1;
        }

        if (!Directory.Exists(scriptsRoot))
        {
            Console.WriteLine($"ERROR: Scripts directory not found: {scriptsRoot}");
            return 1;
        }

        var scripts = CollectScripts(scriptsRoot);

        if (scripts.Count == 0)
        {
            Console.WriteLine("No scripts found in Scripts/ directory.");
            Console.WriteLine("Populate Database/Scripts/ with atomic SQL files first.");
            return 1;
        }

        var outputPath = Path.Combine(dbRoot, "DEV", "DEV_AllInOneInOneGo.sql");
        var outputDir  = Path.GetDirectoryName(outputPath)!;

        if (!Directory.Exists(outputDir))
            Directory.CreateDirectory(outputDir);

        Console.WriteLine($"Building AllInOne from {scripts.Count} script(s)...");
        Console.WriteLine();

        using var writer = new StreamWriter(outputPath, append: false, encoding: System.Text.Encoding.UTF8);

        // File header
        writer.WriteLine("-- =============================================================================");
        writer.WriteLine("-- DEV_AllInOneInOneGo.sql");
        writer.WriteLine("-- AUTO-GENERATED by: pwtools build-allinone");
        writer.WriteLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        writer.WriteLine("-- DO NOT EDIT DIRECTLY — edit scripts in Database/Scripts/ then regenerate.");
        writer.WriteLine("-- =============================================================================");
        writer.WriteLine();

        // Single USE/GO for the whole file
        writer.WriteLine("USE PW_Core_DEV;");
        writer.WriteLine("GO");
        writer.WriteLine();

        foreach (var script in scripts)
        {
            var relativePath = Path.GetRelativePath(scriptsRoot, script);
            Console.WriteLine($"  + {relativePath}");

            writer.WriteLine($"-- -----------------------------------------------------------------------------");
            writer.WriteLine($"-- {relativePath}");
            writer.WriteLine($"-- -----------------------------------------------------------------------------");
            writer.WriteLine();

            var raw     = File.ReadAllText(script, System.Text.Encoding.UTF8);
            var content = StripFileHeader(raw);
            writer.WriteLine(content.TrimEnd());
            writer.WriteLine();
            writer.WriteLine();
        }

        var info = new FileInfo(outputPath);
        Console.WriteLine();
        Console.WriteLine($"AllInOne written:  {outputPath}");
        Console.WriteLine($"Total scripts:     {scripts.Count}");
        Console.WriteLine($"Output size:       {info.Length / 1024} KB");

        return 0;
    }

    internal static List<string> CollectScripts(string scriptsRoot)
    {
        var result = new List<string>();

        // Root-level scripts first
        result.AddRange(
            Directory.GetFiles(scriptsRoot, "*.sql", SearchOption.TopDirectoryOnly)
                     .OrderBy(f => f));

        // Subdirectories in alphanumeric order, files within each in alphanumeric order
        foreach (var dir in Directory.GetDirectories(scriptsRoot).OrderBy(d => d))
        {
            result.AddRange(
                Directory.GetFiles(dir, "*.sql", SearchOption.TopDirectoryOnly)
                         .OrderBy(f => f));
        }

        return result;
    }

    /// <summary>
    /// Strips the per-file USE PW_Core_DEV; GO header so it doesn't repeat
    /// throughout the concatenated AllInOne. Also strips BOM.
    /// </summary>
    private static string StripFileHeader(string content)
    {
        // Strip BOM
        content = content.TrimStart('\uFEFF');

        // Normalise line endings for the regex, restore after
        var normalised = content.Replace("\r\n", "\n").Replace("\r", "\n");

        normalised = Regex.Replace(
            normalised,
            @"^\s*USE\s+PW_Core_DEV\s*;\s*\nGO\s*\n",
            "",
            RegexOptions.IgnoreCase);

        return normalised.TrimStart('\n');
    }
}
