namespace PeasyWare.Tools.Commands;

/// <summary>
/// Concatenates all scripts in Database/Scripts/ into DEV_AllInOneInOneGo.sql
/// in alphanumeric order (directories first, then files within each directory).
///
/// Script collection order:
///   1. Root-level *.sql files (e.g. 000_setup/*.sql)
///   2. Subdirectories in alphanumeric order
///   3. Files within each subdirectory in alphanumeric order
///
/// Each file is preceded by a separator comment showing its relative path.
///
/// Output: Database/DEV/DEV_AllInOneInOneGo.sql
///
/// NOTE: If Scripts/ is empty or not yet split into atomic files,
/// this command will produce an empty or minimal AllInOne.
/// In that case, maintain DEV_AllInOneInOneGo.sql directly until
/// the atomic script split is complete.
/// </summary>
internal static class BuildAllInOneCommand
{
    public static int Run(string[] args)
    {
        string scriptsRoot;
        string dbRoot;

        try
        {
            scriptsRoot = ToolsConfig.GetScriptsRoot();
            dbRoot      = ToolsConfig.GetDatabaseRoot();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"ERROR: {ex.Message}");
            return 1;
        }

        if (!Directory.Exists(scriptsRoot))
        {
            Console.WriteLine($"ERROR: Scripts directory not found: {scriptsRoot}");
            return 1;
        }

        var scripts = CollectScripts(scriptsRoot);

        if (scripts.Count == 0)
        {
            Console.WriteLine("No scripts found in Scripts/ directory.");
            Console.WriteLine("Populate Database/Scripts/ with atomic SQL files first.");
            return 1;
        }

        var outputPath = Path.Combine(dbRoot, "DEV", "DEV_AllInOneInOneGo.sql");
        var outputDir  = Path.GetDirectoryName(outputPath)!;

        if (!Directory.Exists(outputDir))
            Directory.CreateDirectory(outputDir);

        Console.WriteLine($"Building AllInOne from {scripts.Count} script(s)...");
        Console.WriteLine();

        using var writer = new StreamWriter(outputPath, append: false, encoding: System.Text.Encoding.UTF8);

        writer.WriteLine("-- =============================================================================");
        writer.WriteLine("-- DEV_AllInOneInOneGo.sql");
        writer.WriteLine("-- AUTO-GENERATED by: pwtools build-allinone");
        writer.WriteLine($"-- Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        writer.WriteLine("-- DO NOT EDIT DIRECTLY — edit scripts in Database/Scripts/ then regenerate.");
        writer.WriteLine("-- =============================================================================");
        writer.WriteLine();

        foreach (var script in scripts)
        {
            var relativePath = Path.GetRelativePath(scriptsRoot, script);
            Console.WriteLine($"  + {relativePath}");

            writer.WriteLine($"-- -----------------------------------------------------------------------------");
            writer.WriteLine($"-- {relativePath}");
            writer.WriteLine($"-- -----------------------------------------------------------------------------");
            writer.WriteLine();

            var content = File.ReadAllText(script, System.Text.Encoding.UTF8);
            writer.WriteLine(content.TrimEnd());
            writer.WriteLine();
            writer.WriteLine();
        }

        var info = new FileInfo(outputPath);
        Console.WriteLine();
        Console.WriteLine($"AllInOne written:  {outputPath}");
        Console.WriteLine($"Total scripts:     {scripts.Count}");
        Console.WriteLine($"Output size:       {info.Length / 1024} KB");

        return 0;
    }

    internal static List<string> CollectScripts(string scriptsRoot)
    {
        var result = new List<string>();

        // Root-level scripts first
        result.AddRange(
            Directory.GetFiles(scriptsRoot, "*.sql", SearchOption.TopDirectoryOnly)
                     .OrderBy(f => f));

        // Subdirectories in order, files within each in order
        foreach (var dir in Directory.GetDirectories(scriptsRoot).OrderBy(d => d))
        {
            result.AddRange(
                Directory.GetFiles(dir, "*.sql", SearchOption.TopDirectoryOnly)
                         .OrderBy(f => f));
        }

        return result;
    }
}
